yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_lists'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.fields.related import ForeignKey

from .abstract_models import PubdateModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Название группы',
        max_length=200,
        help_text='Ограничение в 200 символов',
    )
    slug = models.SlugField('адрес группы', unique=True)
    description = models.TextField('Описание группы')

    def __str__(self):
        return self.title


class Post(PubdateModel):
    text = models.TextField('Новый пост', help_text='Текст нового поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField('Картинка', upload_to='posts/', blank=True)

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(PubdateModel):
    post = ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Комментарий',
        help_text='текст нового комментария',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        models.UniqueConstraint(
            fields=['user', 'author'], name='unique_follow'
        )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def _page_obj(request, query_set):
    paginator = Paginator(query_set, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.select_related('author', 'group').all()
    context = {
        'page_obj': _page_obj(request, posts),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    group_posts = group.posts.all()
    context = {
        'group': group,
        'page_obj': _page_obj(request, group_posts),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    total = author.posts.count()
    following = Follow.objects.filter(
        user__username=request.user, author=author
    )
    context = {
        'author': author,
        'total': total,
        'page_obj': _page_obj(request, posts),
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    total = post.author.posts.count()
    context = {
        'post': post,
        'total': total,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
        return render(
            request, 'posts/create_post.html', {'form': form, 'is_edit': False}
        )
    form = PostForm()
    return render(
        request, 'posts/create_post.html', {'form': form, 'is_edit': False}
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(
            request.POST, instance=post, files=request.FILES or None
        )
        if form.is_valid():
            post = form.save(commit=False or None)
            post.save()
            return redirect('posts:post_detail', post_id)
        return render(
            request, 'posts/create_post.html', {'form': form, 'is_edit': True}
        )
    form = PostForm(instance=post)
    return render(
        request, 'posts/create_post.html', {'form': form, 'is_edit': True}
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': _page_obj(request, posts),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author).exists()
    if author != request.user and follow is False:
        Follow.objects.create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %} 

{% block content %} 
  <div class="row justify-content-center">
     <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать
          {% else %}
            Новый пост
          {% endif %}                    
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}          
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% csrf_token %}
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
  Лента подписок
{% endblock %}

{% block content %}    
  <h1>Лента подписок</h1>
  {% include "includes/switcher.html" %}
    {% for post in page_obj %}
      <article>
        {% include "includes/article.html" %}
        {% if post.group %}    
          <a href={% url "posts:group_lists" post.group.slug %}>Записи группы "{{ post.group.title }}"</a>
        {% endif %}    
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% include "includes/paginator.html" %}  
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends "base.html" %}

{% block title %}
  Последние публикации группы {{ group.title }}.
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    <article>
      {% include "includes/article.html" %}
    </article>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}     
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}    
  <h1>Последние обновления на сайте</h1>
  {% include "includes/switcher.html" %}
  {% cache 20 page_index page_obj.number %}
    {% for post in page_obj %}
      <article>
        {% include "includes/article.html" %}
        {% if post.group %}    
          <a href={% url "posts:group_lists" post.group.slug %}>Записи группы "{{ post.group.title }}"</a>
        {% endif %}    
      </article>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  {% endcache %} 
  {% include "includes/paginator.html" %}  
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %} 

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %} 
        <li class="list-group-item">
          Группа: {{ post.group.title }}
          <a href={% url "posts:group_lists" post.group.slug %}>
            все записи группы
          </a>
        </li>   
        {% endif %} 
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ total }}</span>
        </li>
        <li class="list-group-item">
          <a href={% url "posts:profile" post.author %}>
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }} 
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url "posts:post_edit" post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
      {% include "includes/comments.html" %}
    </article>
  </div>
{% endblock %} 

yatube/templates/posts/post_list.html
{% extends "base.html" %}

{% block title %}
  Все публикации {{ group.title }}.
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
   <p>
    {{ group.description }}
   </p>
  {% for post in page_obj %}
    <article>
      {% include "includes/article.html" %}
    </article>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include "includes/paginator.html" %}   
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %} 

{% block content %}
  <div class="mb-5">  
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ total }} </h3>
    {% if request.user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url "posts:profile_unfollow" author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url "posts:profile_follow" author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}   
    <article>
      {% include "includes/article.html"%}
    </article>     
    {% if post.group %}    
      <a href={% url "posts:group_lists" post.group.slug %}>все записи группы "{{ post.group.title }}"</a>
    {% endif %}       
    <hr>
  {% endfor %} 
  {% include "includes/paginator.html" %}
{% endblock %} 